
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session  = await getServerSession()
  return (
    <html lang="en" className='h-screen'>
      <body className={inter.className + "w-screen h-screen relative"}>
        <Navbar session={session}/>
        {children}
      </body>
    </html>
  )
}
